FROM rocker/shiny:4.0.3

RUN apt-get update && apt-get install libcurl4-openssl-dev libv8-dev -y &&\
  mkdir -p /var/lib/shiny-server/bookmarks/shiny

# Download and install library
RUN install2.r -e shinydashboard shinyjs V8 tibble stringr digest jsonlite dplyr config DT ggplot2 
RUN install2.r -e devtools here psych plumber doParallel groupdata2 dataPreparation glmnet broom usethis GPArotation tidyr png rmarkdown
#install.packages(c('shinydashboard', 'shinyjs', 'V8'))"

RUN R -e 'devtools::install_github(c("jasongullifer/languageentropy", "rstudio/plumber"))'

COPY languageEntropyPredictor_0.0.1.0000.tar.gz /packages/languageEntropyPredictor_0.0.1.0000.tar.gz
RUN install2.r -e /packages/languageEntropyPredictor_0.0.1.0000.tar.gz

# copy the app to the image COPY shinyapps /srv/shiny-server/
# make all app files readable (solves issue when dev in Windows, but building in Ubuntu)
RUN chmod -R 755 /srv/shiny-server/

EXPOSE 80
EXPOSE 3838

ENTRYPOINT ["R", "-e", \
    "languageEntropyPredictor::runShinyFrontend(host='0.0.0.0', port = 8000, api_url='206.12.95.103', api_port = 8080)"]